services:
  qdrant-db:
    image: qdrant/qdrant
    container_name: qdrant-db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  bot:
    build: .
    container_name: company-info-bot
    env_file:
      - .env
    depends_on:
      - qdrant-db
    volumes:
      - ./documents:/app/documents
    entrypoint: ["sh", "-c", "python ingest.py && python bot.py"]
    network_mode: host

volumes:
  qdrant_data:
